# Generated by Django 5.2.17 on 2026-08-15 19:14

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_analytics_tracked_orderlinediscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="code",
            field=oscar.models.fields.NullCharField(
                max_length=255, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="code",
            field=oscar.models.fields.NullCharField(
                max_length=255, unique=True, verbose_name="Code"
            ),
        ),
    ]
