# Generated by Django 2.2.12 on 2020-05-11 14:11

from django.db import migrations, models
import django.contrib.postgres.fields.hstore
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
        ("cch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingTaxation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cch_line_id", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=5)),
                ("state_code", models.CharField(max_length=5)),
                (
                    "total_tax_applied",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_taxations",
                        to="order.Order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "cch_line_id")},
            },
        ),
        migrations.CreateModel(
            name="ShippingTaxationDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "taxation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="cch.ShippingTaxation",
                    ),
                ),
            ],
        ),
    ]
