# Generated by Django 6.1 on 2026-08-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cch", "0002_shippingtaxation_shippingtaxationdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertaxation",
            name="transaction_id",
            field=models.BigIntegerField(),
        ),
    ]
