# Generated by Django 6.1 on 2026-08-31 20:21
#
# Deploy note: on PostgreSQL the integer -> bigint change rewrites the whole
# cch_ordertaxation table under an ACCESS EXCLUSIVE lock, blocking checkout
# writes for the duration. Reversing fails with "integer out of range" once any
# SureTax transaction ID above 2**31 - 1 has been stored.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cch", "0002_shippingtaxation_shippingtaxationdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertaxation",
            name="transaction_id",
            field=models.BigIntegerField(),
        ),
    ]
